# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  sofy: sofy-dot-ai/sofy@0.1.8
  android: circleci/android@0.2.0
# Orchestrate or schedule a set of jobs
jobs: 
  sofy_job: 
    docker:       
      - image: buildpack-deps:trusty        
    steps:
      - run: git clone "https://github.com/codinguser/gnucash-android.git"
      - run: cd "gnucash-android"
      - sofy/connect_sofy:
          subscription_key: "acc80bd1-5cb7-4c89-a01e-2e7169009e52"
          apk_path: "C:/Users/shahm/Downloads/app.apk"
workflows:
  # Name the workflow "welcome"
  send job:
    # Run the welcome/run job in its own container
    jobs:
      - sofy_job

