# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb
orbs:
  # Declare a dependency on the sofy-orb
  sofy: sofy-ai/sofy@1.1.1
# Orchestrate or schedule a set of jobs
jobs:
   build_job:
      docker:
         - image: circleci/android:api-29
   steps:
	  - run: curl https://portalvhdsld5gs9t7pkkvf.blob.core.windows.net/quantyzdandroidruns/c962bee0-6ebd-4a95-8653-c2166b021b16_Nothing_v1.6.2_apkpure.comeecd0050-1722-4452-bb53-851baeb3fdb5.apk --output app.apk
          - sofy/connect_sofy:
	       subscription_key: "31f4313b-d81c-46a0-9ce0-77c658380149"
	       build_path: "/home/circleci/project/app.apk"
workflows:
# Name the workflow "buildJob
   appbuild:
      jobs:
         - build_job
