# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  sofy: sofy-dot-ai/sofy@0.2.0
# Orchestrate or schedule a set of jobs
jobs: 
  sofy_job:
    docker:       
      - image: circleci/android:api-29         
    steps:
      - sofy/connect_sofy:
          subscription_key: "acc80bd1-5cb7-4c89-a01e-2e7169009e52"
          apk_path: "/home/circleci/project/app.apk"
workflows:
  # Name the workflow "welcome"
  sendjob:
    # Run the welcome/run job in its own container
    jobs:
      - sofy_job

