# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  sofy: sofy-ai/sofy@1.1.1
# Orchestrate or schedule a set of jobs
jobs: 
  sofy_job:
    docker:       
      - image: circleci/android:api-29         
    steps:
      - run: curl https://portalvhdsld5gs9t7pkkvf.blob.core.windows.net/quantyzdandroidruns/c962bee0-6ebd-4a95-8653-c2166b021b16_Nothing_v1.6.2_apkpure.comeecd0050-1722-4452-bb53-851baeb3fdb5.apk --output app.apk
      - sofy/connect_sofy:
          subscription_key: "8ea4fed8-afdf-49a8-a740-afad05addd3a"
          build_path: "/home/circleci/project/app.apk"
workflows:
  # Name the workflow "welcome"
  sendjob:
    # Run the welcome/run job in its own container
    jobs:
      - sofy_job

